### ISSUE TITLE
Blat runtime

### ISSUE THREAD

**Issue by PamelaMehanna** [AugustHuang/MosaicHunter#1]
Hi,

I am running MosaicHunter on a WES sample (6.6 GB). Step 1 was completed in ~2h. I am now running step2 with mem=96GB. After this line:
`Tue Mar 06 10:14:20 EST 2018 - Time(s):521 Reads:46191861 Sites:3095677412/3095677412 Progress:100.00%`
the Blat step started. But it's been 10 hours of runtime and it isn't done yet. 
Is it normal? What is the average runtime of step2 for a WES sample?

Thank you.

**Comment by AugustHuang** [comment]
Hi Pamela,

This is normal. BLAT is used to re-align the reads spanning candidate
somatic mutations called in step 2, though it runs quiet slowly. In my
experience, it would be finished within 1 day for a WES sample with default
parameters.

Best,
August

**Comment by PamelaMehanna** [comment]
Thank you!
